[package]
name = "hidden_functionality"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }     # Required for actix-web
serde = { version = "1.0", features = ["derive"] } # <-- ADD THIS LINE
serde_json = "1.0"
